# Generated by Django 3.0.5 on 2020-04-10 19:50


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('kind', models.IntegerField(choices=[(1, 'لباس'), (2, 'شلوار'), (3, 'کفش')])),
            ],
            options={
                'verbose_name': 'لباس',
                'verbose_name_plural': 'لباس',
            },
        ),
    ]
