# Generated by Django 3.0.5 on 2020-04-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothe',
            new_name='Clothing',
        ),
    ]
